// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexoCPM.Persistence.Context;

#nullable disable

namespace NexoCPM.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260421201058_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NexoCPM.Domain.Auth.Entities.EmailVerificationToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ncp_email_verification_token", (string)null);
                });

            modelBuilder.Entity("NexoCPM.Domain.Auth.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Revoked")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ncp_refresh_token", (string)null);
                });

            modelBuilder.Entity("NexoCPM.Domain.Context.Entities.Competence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EffectYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ncp_competence", (string)null);
                });

            modelBuilder.Entity("NexoCPM.Domain.Context.Entities.CompetenceLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CompetenceId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LevelNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompetenceId");

                    b.ToTable("ncp_competence_level", (string)null);
                });

            modelBuilder.Entity("NexoCPM.Domain.Context.Entities.CompetenceLevelUnit", b =>
                {
                    b.Property<int>("CompetenceLevelId")
                        .HasColumnType("int");

                    b.Property<int>("SyllabusUnitId")
                        .HasColumnType("int");

                    b.HasKey("CompetenceLevelId", "SyllabusUnitId");

                    b.HasIndex("SyllabusUnitId");

                    b.ToTable("ncp_competence_level_unit", (string)null);
                });

            modelBuilder.Entity("NexoCPM.Domain.Context.Entities.EducationContext", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<int?>("SpecializationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecializationId");

                    b.HasIndex("LevelId", "SpecializationId")
                        .IsUnique()
                        .HasFilter("[SpecializationId] IS NOT NULL");

                    b.ToTable("ncp_education_context", (string)null);
                });

            modelBuilder.Entity("NexoCPM.Domain.Context.Entities.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ModalityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModalityId");

                    b.ToTable("ncp_level", (string)null);
                });

            modelBuilder.Entity("NexoCPM.Domain.Context.Entities.Modality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ncp_modality", (string)null);
                });

            modelBuilder.Entity("NexoCPM.Domain.Context.Entities.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ncp_specialization", (string)null);
                });

            modelBuilder.Entity("NexoCPM.Domain.Curriculum.Entities.MicroTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("SubTopicId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubTopicId");

                    b.ToTable("ncp_micro_topic", (string)null);
                });

            modelBuilder.Entity("NexoCPM.Domain.Curriculum.Entities.SubTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("ncp_sub_topic", (string)null);
                });

            modelBuilder.Entity("NexoCPM.Domain.Curriculum.Entities.Syllabus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EfectYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ncp_syllabus", (string)null);
                });

            modelBuilder.Entity("NexoCPM.Domain.Curriculum.Entities.SyllabusContext", b =>
                {
                    b.Property<int>("SyllabusId")
                        .HasColumnType("int");

                    b.Property<int>("EducationContextId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("SyllabusId", "EducationContextId");

                    b.HasIndex("EducationContextId");

                    b.ToTable("ncp_syllabus_context", (string)null);
                });

            modelBuilder.Entity("NexoCPM.Domain.Curriculum.Entities.SyllabusUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("SyllabusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SyllabusId");

                    b.ToTable("ncp_syllabus_unit", (string)null);
                });

            modelBuilder.Entity("NexoCPM.Domain.Curriculum.Entities.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("SyllabusUnitId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SyllabusUnitId");

                    b.ToTable("ncp_topic", (string)null);
                });

            modelBuilder.Entity("NexoCPM.Domain.Evaluations.Entities.Assessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<int>("NumberQuestions")
                        .HasColumnType("int");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.Property<int?>("TargetId")
                        .HasColumnType("int");

                    b.Property<int?>("TimeLimitSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Scope", "TargetId");

                    b.ToTable("ncp_assessment", (string)null);
                });

            modelBuilder.Entity("NexoCPM.Domain.Evaluations.Entities.AssessmentAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("int");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UserLearningContextId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserLearningContextId");

                    b.ToTable("ncp_assesment_attempt", (string)null);
                });

            modelBuilder.Entity("NexoCPM.Domain.Evaluations.Entities.AssessmentAttemptQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssessmentAttemptId")
                        .HasColumnType("int");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("SecondsSpent")
                        .HasColumnType("int");

                    b.Property<int?>("SelectedOptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SelectedOptionId");

                    b.HasIndex("AssessmentAttemptId", "QuestionId")
                        .IsUnique();

                    b.ToTable("ncp_assessment_attempt_question", (string)null);
                });

            modelBuilder.Entity("NexoCPM.Domain.Evaluations.Entities.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("ncp_option", (string)null);
                });

            modelBuilder.Entity("NexoCPM.Domain.Evaluations.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SubTopicId")
                        .HasColumnType("int");

                    b.Property<int>("TotalAttempts")
                        .HasColumnType("int");

                    b.Property<int>("TotalCorrect")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("SubTopicId");

                    b.ToTable("ncp_question", (string)null);
                });

            modelBuilder.Entity("NexoCPM.Domain.Evaluations.Entities.QuestionContentBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("QuestionId");

                    b.ToTable("ncp_question_content_block", (string)null);
                });

            modelBuilder.Entity("NexoCPM.Domain.Resources.Entities.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LikesCount")
                        .HasColumnType("int");

                    b.Property<int>("PublicScore")
                        .HasColumnType("int");

                    b.Property<int?>("SubTopicId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubTopicId");

                    b.ToTable("ncp_resource", (string)null);
                });

            modelBuilder.Entity("NexoCPM.Domain.Resources.Entities.ResourceLike", b =>
                {
                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ResourceId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ncp_resource_like", (string)null);
                });

            modelBuilder.Entity("NexoCPM.Domain.Users.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LinkedInProfile")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("ncp_user", (string)null);
                });

            modelBuilder.Entity("NexoCPM.Domain.Users.Entities.UserLearningContext", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SyllabusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SyllabusId");

                    b.HasIndex("UserId");

                    b.ToTable("ncp_user_learning_context", (string)null);
                });

            modelBuilder.Entity("NexoCPM.Domain.Users.Entities.UserResourceView", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "ResourceId");

                    b.HasIndex("ResourceId");

                    b.ToTable("ncp_user_resource_view", (string)null);
                });

            modelBuilder.Entity("NexoCPM.Domain.Users.Entities.UserSyllabusProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastAccess")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UserLearningContextId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserLearningContextId")
                        .IsUnique();

                    b.ToTable("ncp_user_syllabus_progress", (string)null);
                });

            modelBuilder.Entity("NexoCPM.Domain.Users.Entities.UserSyllabusUnitProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastAttemptAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SyllabusUnitId")
                        .HasColumnType("int");

                    b.Property<int>("TotalCorrect")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UserSyllabusProgressId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SyllabusUnitId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserSyllabusProgressId", "SyllabusUnitId")
                        .IsUnique();

                    b.ToTable("ncp_user_syllabus_unit_progress", (string)null);
                });

            modelBuilder.Entity("NexoCPM.Domain.Auth.Entities.EmailVerificationToken", b =>
                {
                    b.HasOne("NexoCPM.Domain.Users.Entities.User", "User")
                        .WithMany("EmailVerificationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexoCPM.Domain.Auth.Entities.RefreshToken", b =>
                {
                    b.HasOne("NexoCPM.Domain.Users.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexoCPM.Domain.Context.Entities.CompetenceLevel", b =>
                {
                    b.HasOne("NexoCPM.Domain.Context.Entities.Competence", "Competence")
                        .WithMany("CompetenceLevels")
                        .HasForeignKey("CompetenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competence");
                });

            modelBuilder.Entity("NexoCPM.Domain.Context.Entities.CompetenceLevelUnit", b =>
                {
                    b.HasOne("NexoCPM.Domain.Context.Entities.CompetenceLevel", "CompetenceLevel")
                        .WithMany("CompetenceLevelUnits")
                        .HasForeignKey("CompetenceLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexoCPM.Domain.Curriculum.Entities.SyllabusUnit", "SyllabusUnit")
                        .WithMany("CompetenceLevelUnits")
                        .HasForeignKey("SyllabusUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompetenceLevel");

                    b.Navigation("SyllabusUnit");
                });

            modelBuilder.Entity("NexoCPM.Domain.Context.Entities.EducationContext", b =>
                {
                    b.HasOne("NexoCPM.Domain.Context.Entities.Level", "Level")
                        .WithMany("EducationContexts")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexoCPM.Domain.Context.Entities.Specialization", "Specialization")
                        .WithMany("EducationContexts")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Level");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("NexoCPM.Domain.Context.Entities.Level", b =>
                {
                    b.HasOne("NexoCPM.Domain.Context.Entities.Modality", "Modality")
                        .WithMany("Levels")
                        .HasForeignKey("ModalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modality");
                });

            modelBuilder.Entity("NexoCPM.Domain.Curriculum.Entities.MicroTopic", b =>
                {
                    b.HasOne("NexoCPM.Domain.Curriculum.Entities.SubTopic", "SubTopic")
                        .WithMany("MicroTopics")
                        .HasForeignKey("SubTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubTopic");
                });

            modelBuilder.Entity("NexoCPM.Domain.Curriculum.Entities.SubTopic", b =>
                {
                    b.HasOne("NexoCPM.Domain.Curriculum.Entities.Topic", "Topic")
                        .WithMany("SubTopics")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("NexoCPM.Domain.Curriculum.Entities.SyllabusContext", b =>
                {
                    b.HasOne("NexoCPM.Domain.Context.Entities.EducationContext", "EducationContext")
                        .WithMany("SyllabusContexts")
                        .HasForeignKey("EducationContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexoCPM.Domain.Curriculum.Entities.Syllabus", "Syllabus")
                        .WithMany("SyllabusContexts")
                        .HasForeignKey("SyllabusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationContext");

                    b.Navigation("Syllabus");
                });

            modelBuilder.Entity("NexoCPM.Domain.Curriculum.Entities.SyllabusUnit", b =>
                {
                    b.HasOne("NexoCPM.Domain.Curriculum.Entities.Syllabus", "Syllabus")
                        .WithMany("SyllabusUnits")
                        .HasForeignKey("SyllabusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Syllabus");
                });

            modelBuilder.Entity("NexoCPM.Domain.Curriculum.Entities.Topic", b =>
                {
                    b.HasOne("NexoCPM.Domain.Curriculum.Entities.SyllabusUnit", "SyllabusUnit")
                        .WithMany("Topics")
                        .HasForeignKey("SyllabusUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SyllabusUnit");
                });

            modelBuilder.Entity("NexoCPM.Domain.Evaluations.Entities.AssessmentAttempt", b =>
                {
                    b.HasOne("NexoCPM.Domain.Evaluations.Entities.Assessment", "Assessment")
                        .WithMany("AssessmentAttempts")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexoCPM.Domain.Users.Entities.User", null)
                        .WithMany("AssessmentAttempts")
                        .HasForeignKey("UserId");

                    b.HasOne("NexoCPM.Domain.Users.Entities.UserLearningContext", "UserLearningContext")
                        .WithMany("AssessmentAttempts")
                        .HasForeignKey("UserLearningContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("UserLearningContext");
                });

            modelBuilder.Entity("NexoCPM.Domain.Evaluations.Entities.AssessmentAttemptQuestion", b =>
                {
                    b.HasOne("NexoCPM.Domain.Evaluations.Entities.AssessmentAttempt", "AssessmentAttempt")
                        .WithMany("AssessmentAttemptQuestions")
                        .HasForeignKey("AssessmentAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexoCPM.Domain.Evaluations.Entities.Question", "Question")
                        .WithMany("AssessmentAttemptQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexoCPM.Domain.Evaluations.Entities.Option", "SelectedOption")
                        .WithMany("AssessmentAttemptQuestions")
                        .HasForeignKey("SelectedOptionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AssessmentAttempt");

                    b.Navigation("Question");

                    b.Navigation("SelectedOption");
                });

            modelBuilder.Entity("NexoCPM.Domain.Evaluations.Entities.Option", b =>
                {
                    b.HasOne("NexoCPM.Domain.Evaluations.Entities.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("NexoCPM.Domain.Evaluations.Entities.Question", b =>
                {
                    b.HasOne("NexoCPM.Domain.Curriculum.Entities.SubTopic", "SubTopic")
                        .WithMany("Questions")
                        .HasForeignKey("SubTopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubTopic");
                });

            modelBuilder.Entity("NexoCPM.Domain.Evaluations.Entities.QuestionContentBlock", b =>
                {
                    b.HasOne("NexoCPM.Domain.Evaluations.Entities.Question", "Question")
                        .WithMany("QuestionContentBlocks")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("NexoCPM.Domain.Resources.Entities.Resource", b =>
                {
                    b.HasOne("NexoCPM.Domain.Curriculum.Entities.SubTopic", "SubTopic")
                        .WithMany("Resources")
                        .HasForeignKey("SubTopicId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("SubTopic");
                });

            modelBuilder.Entity("NexoCPM.Domain.Resources.Entities.ResourceLike", b =>
                {
                    b.HasOne("NexoCPM.Domain.Resources.Entities.Resource", "Resource")
                        .WithMany("ResourceLikes")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexoCPM.Domain.Users.Entities.User", "User")
                        .WithMany("ResourceLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexoCPM.Domain.Users.Entities.UserLearningContext", b =>
                {
                    b.HasOne("NexoCPM.Domain.Curriculum.Entities.Syllabus", "Syllabus")
                        .WithMany("UserLearningContexts")
                        .HasForeignKey("SyllabusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexoCPM.Domain.Users.Entities.User", "User")
                        .WithMany("UserLearningContexts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Syllabus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexoCPM.Domain.Users.Entities.UserResourceView", b =>
                {
                    b.HasOne("NexoCPM.Domain.Resources.Entities.Resource", "Resource")
                        .WithMany("UserResourceViews")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexoCPM.Domain.Users.Entities.User", "User")
                        .WithMany("UserResourceViews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexoCPM.Domain.Users.Entities.UserSyllabusProgress", b =>
                {
                    b.HasOne("NexoCPM.Domain.Users.Entities.User", null)
                        .WithMany("UserSyllabusProgresses")
                        .HasForeignKey("UserId");

                    b.HasOne("NexoCPM.Domain.Users.Entities.UserLearningContext", "UserLearningContext")
                        .WithOne("UserSyllabusProgress")
                        .HasForeignKey("NexoCPM.Domain.Users.Entities.UserSyllabusProgress", "UserLearningContextId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserLearningContext");
                });

            modelBuilder.Entity("NexoCPM.Domain.Users.Entities.UserSyllabusUnitProgress", b =>
                {
                    b.HasOne("NexoCPM.Domain.Curriculum.Entities.SyllabusUnit", "SyllabusUnit")
                        .WithMany("UserSyllabusUnitProgresses")
                        .HasForeignKey("SyllabusUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexoCPM.Domain.Users.Entities.User", null)
                        .WithMany("UserSyllabusUnitProgresses")
                        .HasForeignKey("UserId");

                    b.HasOne("NexoCPM.Domain.Users.Entities.UserSyllabusProgress", "UserSyllabusProgress")
                        .WithMany()
                        .HasForeignKey("UserSyllabusProgressId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("SyllabusUnit");

                    b.Navigation("UserSyllabusProgress");
                });

            modelBuilder.Entity("NexoCPM.Domain.Context.Entities.Competence", b =>
                {
                    b.Navigation("CompetenceLevels");
                });

            modelBuilder.Entity("NexoCPM.Domain.Context.Entities.CompetenceLevel", b =>
                {
                    b.Navigation("CompetenceLevelUnits");
                });

            modelBuilder.Entity("NexoCPM.Domain.Context.Entities.EducationContext", b =>
                {
                    b.Navigation("SyllabusContexts");
                });

            modelBuilder.Entity("NexoCPM.Domain.Context.Entities.Level", b =>
                {
                    b.Navigation("EducationContexts");
                });

            modelBuilder.Entity("NexoCPM.Domain.Context.Entities.Modality", b =>
                {
                    b.Navigation("Levels");
                });

            modelBuilder.Entity("NexoCPM.Domain.Context.Entities.Specialization", b =>
                {
                    b.Navigation("EducationContexts");
                });

            modelBuilder.Entity("NexoCPM.Domain.Curriculum.Entities.SubTopic", b =>
                {
                    b.Navigation("MicroTopics");

                    b.Navigation("Questions");

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("NexoCPM.Domain.Curriculum.Entities.Syllabus", b =>
                {
                    b.Navigation("SyllabusContexts");

                    b.Navigation("SyllabusUnits");

                    b.Navigation("UserLearningContexts");
                });

            modelBuilder.Entity("NexoCPM.Domain.Curriculum.Entities.SyllabusUnit", b =>
                {
                    b.Navigation("CompetenceLevelUnits");

                    b.Navigation("Topics");

                    b.Navigation("UserSyllabusUnitProgresses");
                });

            modelBuilder.Entity("NexoCPM.Domain.Curriculum.Entities.Topic", b =>
                {
                    b.Navigation("SubTopics");
                });

            modelBuilder.Entity("NexoCPM.Domain.Evaluations.Entities.Assessment", b =>
                {
                    b.Navigation("AssessmentAttempts");
                });

            modelBuilder.Entity("NexoCPM.Domain.Evaluations.Entities.AssessmentAttempt", b =>
                {
                    b.Navigation("AssessmentAttemptQuestions");
                });

            modelBuilder.Entity("NexoCPM.Domain.Evaluations.Entities.Option", b =>
                {
                    b.Navigation("AssessmentAttemptQuestions");
                });

            modelBuilder.Entity("NexoCPM.Domain.Evaluations.Entities.Question", b =>
                {
                    b.Navigation("AssessmentAttemptQuestions");

                    b.Navigation("Options");

                    b.Navigation("QuestionContentBlocks");
                });

            modelBuilder.Entity("NexoCPM.Domain.Resources.Entities.Resource", b =>
                {
                    b.Navigation("ResourceLikes");

                    b.Navigation("UserResourceViews");
                });

            modelBuilder.Entity("NexoCPM.Domain.Users.Entities.User", b =>
                {
                    b.Navigation("AssessmentAttempts");

                    b.Navigation("EmailVerificationTokens");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ResourceLikes");

                    b.Navigation("UserLearningContexts");

                    b.Navigation("UserResourceViews");

                    b.Navigation("UserSyllabusProgresses");

                    b.Navigation("UserSyllabusUnitProgresses");
                });

            modelBuilder.Entity("NexoCPM.Domain.Users.Entities.UserLearningContext", b =>
                {
                    b.Navigation("AssessmentAttempts");

                    b.Navigation("UserSyllabusProgress")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
